# Feel free to edit. Mind all your own comments or white-spaces may be stripped by configuration save peformed by application.

update: http://jcloisterzone.com/version.xml
port: 37447

# keep empty for system language or fill to force locale
# supported locales are cs, de, en, es, fr, hu, it, pl, ro, ru, sk
locale: 

score_display_duration: 7 # seconds
ai_place_tile_delay: 250 # miliseconds to wait before computer player place tile

beep_alert: false
confirm: 
  farm_place: false
  game_close: true
  ransom_payment: true
  tower_place: true

players:
  # Colors as Java awt.Color constant or in hex-value. (third-party themes can ignore these colors)
  colors: 
  - {font: null, meeple: RED}
  - {font: null, meeple: '#008ffe'}
  - {font: null, meeple: '#FFED00'}
  - {font: null, meeple: '#009900'}
  - {font: null, meeple: BLACK}
  - {font: null, meeple: '#812EFF'}

  # You can declare default player names
  names: 
  ai_names: [Adda, Ellen, Caitlyn, Riannon, Tankred, Rigatona]

# plugins/classic.jar - Graphics from original board game
# plugins/rgg_siege.jar - RGG's Siege tiles instead of original The Cathars tiles
plugins: 
  - plugins/classic.jar

# possible expansions in profile definition:
#   WINTER, INNS_AND_CATHEDRALS, TRADERS_AND_BUILDERS, PRINCESS_AND_DRAGON,
#   TOWER, ABBEY_AND_MAYOR, BRIDGES_CASTLES_AND_BAZAARS, CATAPULT,
#   KING_AND_ROBBER_BARON, RIVER, RIVER_II, CATHARS, BESIEGERS, COUNT,
#   GQ11, CULT, TUNNEL, CORN_CIRCLES, PLAGUE, FESTIVAL, PHANTOM, WIND_ROSE,
#   FLIER, CORN_CIRCLES_II
#
# possible rules:
#   RANDOM_SEATING_ORDER,
#   TINY_CITY_2_POINTS, PRINCESS_MUST_REMOVE_KNIGHT,
#   DRAGON_MOVE_AFTER_SCORING, ESCAPE_RGG, PIG_HERD_ON_GQ_FARM,
#   MULTI_BARN_ALLOWEDD, TUNNELIZE_ALL_EXPANSIONS,  BAZAAR_NO_AUCTION,

presets: 

connection_history: 



