--- #JCloisterZone configuration
update: http://jcloisterzone.com/version.xml
port: 37447

# keep empty for system language or fill to force locale, supported locales are cs, de, en, es, fr, hu, it, pl, ro, ru, sk
locale:

score_display_duration: 7 # seconds
ai_place_tile_delay: 250 # miliseconds to wait before computer player place tile

beep_alert: false
confirm:
  farm_place: false
  tower_place: true
  game_close: true
  ransom_payment: true

players:
  colors: # Colors as Java awt.Color constant or in hex-value. (third-party themes can ignore these colors)
    - RED
    - "#008ffe"
    - YELLOW
    - "#009900"
    - BLACK
    - "#808000"

  names: [] # You can declare default player names
  ai_names: [ Adda, Ellen, Caitlyn, Riannon, Tankred, Rigatona ]

plugins:
  - plugins/classic.jar # Graphics from original board game
  #- plugins/rgg_siege.jar # RGG's Siege tiles instead of original The Cathars tiles

profiles:
  default:
    expansions:
      #- WINTER
      #- INNS_AND_CATHEDRALS
      #- TRADERS_AND_BUILDERS
      #- PRINCESS_AND_DRAGON
      #- TOWER
      #- ABBEY_AND_MAYOR
      #- BRIDGES_CASTLES_AND_BAZAARS

      #- CATAPULT
      #- KING_AND_SCOUT
      #- RIVER
      #- RIVER_II
      #- CATHARS= false
      #- COUNT= false
      #- GQ11= false
      #- CULT
      #- TUNNEL
      #- CORN_CIRCLES
      #- PLAGUE
      #- FESTIVAL
      #- PHANTOM
      #- WIND_ROSE

      #- FLIER
      #- CORN_CIRCLES_II
    rules:
      #- TINY_CITY_2_POINTS
      #- FARM_CITY_SCORED_ONCE
      #- CANNOT_PLACE_BUILDER_ON_VOLCANO
      #- PRINCESS_MUST_REMOVE_KNIGHT
      - PIG_HERD_ON_GQ_FARM
      #- MULTI_BARN_ALLOWEDD
      - TUNNELIZE_ALL_EXPANSIONS
      #- BAZAAR_NO_AUCTION


